#!/bin/bash

# aim of this script is to run kraken on a list of files as a job array

#3 positional arguments are mandatory - kill script if any are absent
if [ $# -ne 1 ]
then
echo "This script will take all the kraken reports  in a directory"
echo "And run bracken on them as a jobarray"
echo "They'll have the same name but .bracken added"
echo "Invalid number of positional arguments "
 echo "cmd <krakendb>"
 exit 1
fi


DB=$1


LANES_ARRAY=($(ls -1 *.report | rev | cut -c8- | rev))


NJOBS=${#LANES_ARRAY[@]} 
echo ""
echo "I'm gonna get all the kraken reports in this directory and run bracken on em."
echo "Submitted as a job array"
echo ""
echo "Number of _1 reports:"
echo $NJOBS

echo "Write these filenames to lanes.txt?"
echo "And make the outputdir?"
echo "And submit em as kraken job?"

read -p "Press enter to continue"


rm lanes.txt -f 

printf "%s\n" "${LANES_ARRAY[@]}" > lanes.txt

mkdir bracken_logs

#bsub -J "kraken[1-$NJOBS]" -o $OUTPUTDIR/logs/kraken.%J.%I.o -e $OUTPUTDIR/logs/kraken.%J.%I.e -R 'select[mem>8000] rusage[mem=8000]' -M8000 -n 8 -R 'span[hosts=1]' "submit-kraken-job-array  $DB $OUTPUTDIR" 


bsub -J "bracken[1-$NJOBS]" -o bracken_logs/bracken.%J.%I.o -e bracken_logs/bracken.%J.%I.e -R 'select[mem>1000] rusage[mem=1000]' -M1000 "submit-bracken-job-array  $DB" 


echo ""
echo "Now go and have a nice cup of tea"

