#!/bin/bash


if [ $# -ne 3 ]
then
echo "This script will run prokka as a job array"
echo "It wants input file of file namesi (text file, one per line)"
echo "And a genus to run its models"
echo ""
 echo "cmd <inputfile> <outputdir> <genus>"
 exit 1
fi

INPUTFILE=$1
#FASTA_ARRAY=($(find $2 -name "*.fa"))
FASTA_ARRAY=($(cat $INPUTFILE))
OUTPUTDIR=$2
GENUS=$3
NJOBS=${#FASTA_ARRAY[@]} 
echo ""
echo "I'm gonna run prokka on these"
echo "Submitted as a job array"
echo ""
echo "Number of fastas:" $NJOBS

echo "Make the outputdir?"
echo "And submit em with bsub?"

read -p "Press any key to continue: ctrl-C to quit"


mkdir $OUTPUTDIR
mkdir $OUTPUTDIR/logs
#rm fastas_for_prokka.txt -f 

#printf "%s\n" "${FASTA_ARRAY[@]}" > fastas_for_prokka.txt


bsub -J "prokka[1-$NJOBS]" -o $OUTPUTDIR/logs/prokka.%J.%I.o -e $OUTPUTDIR/logs/prokka.%J.%I.e -R 'select[mem>1000] rusage[mem=1000]' -M1000 -n 1 -R "span[hosts=1]"  "submit-prokka-job-array $INPUTFILE $OUTPUTDIR $GENUS"

