##Configuration file for snippy_snakemake
#Path to read directory
reads: /Users/sarah.gallichan/Documents/Pipe_test/Reads
#File extension that comes after sample names
R1_suffix: _1.fastq.gz
R2_suffix: _2.fastq.gz
#Path to output
output: /Users/sarah.gallichan/Documents/Pipe_test